server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh-food?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  # Config mail
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: freshshop2711@gmail.com
#    password: Freshshop@2711
#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            port : 465
#            class : javax.net.ssl.SSLSocketFactory
#            fallback : false
#          auth: true
#          connectiontimeout : 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable : true
#      debug: true
#      transport:
#        protocol: smtp

# Secret JWT APP
ducninh:
  app:
    jwtSecret: Fresh-Food
    jwtExpiration: 86400000

# Location resource folder
location:
  resource: /opt/fresh-food/resource/
