server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh-food?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

# Secret JWT APP
ducninh:
  app:
    jwtSecret: Fresh-Food
    jwtExpiration: 86400000

# Location resource folder
location:
  resource: /opt/fresh-food/resource/

# Config mail
config:
  mail:
    host: smtp.gmail.com
    port: 587
    username: freshshop2711@gmail.com
    password: Freshshop@2711
